title: Docs for the AR_project
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://cheningfrank.github.io/ai

aux_links:
  Github Repository: 
